project_id = "ktaimgprslmzwygvgpmf"

[functions.admin-overview]
verify_jwt = false

[functions.admin-free-embeds]
verify_jwt = false

[functions.admin-pro-assets]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.asset-status-webhook]
verify_jwt = false

[functions.admin-control]
verify_jwt = false

[functions.payfast-itn]
verify_jwt = false

[functions.create-payfast-payment]
verify_jwt = false